"""
pdf_generator.py
----------------
Converts the list of scraped GFG article dicts into a professional
academic PDF that looks like a college instructional module.

Layout per article:
  ┌─────────────────────────────────────────────────────────────┐
  │  HEADER  — Subject Category | Date of Generation            │
  ├─────────────────────────────────────────────────────────────┤
  │  TOPIC TITLE  (large, highlighted)                          │
  │  Difficulty Level badge                                     │
  │  ─────────────────────────────────────────────────────────  │
  │  KEY TECHNICAL CONCEPTS                                     │
  │  …text…                                                     │
  │  CODE SNIPPETS / IMPLEMENTATION                             │
  │  …monospace code box…                                       │
  │  COMPLEXITY ANALYSIS                                        │
  │  …text…                                                     │
  │  REFERENCES / RELATED LINKS                                 │
  │  • link text (url)                                          │
  ├─────────────────────────────────────────────────────────────┤
  │  FOOTER  — Page N  |  "Generated by GFG Linux Scraper"     │
  └─────────────────────────────────────────────────────────────┘
"""

import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, Preformatted
)
from reportlab.platypus import BaseDocTemplate, PageTemplate, Frame
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ── Constants ─────────────────────────────────────────────────────────────────
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
GENERATOR_NAME = "GFG Linux Academic Scraper"
SUBJECT_CATEGORY = "Linux Operating System — Technical Reference"

# Brand colours (GFG green palette + neutral academic grays)
GFG_GREEN  = colors.HexColor("#2F8D46")   # GFG primary green
GFG_DARK   = colors.HexColor("#1a5c2e")   # dark green for headings
LIGHT_BG   = colors.HexColor("#f0faf3")   # very light green tint
CODE_BG    = colors.HexColor("#1e1e1e")   # dark code background
CODE_FG    = colors.HexColor("#d4d4d4")   # light text for code
GRAY_LINE  = colors.HexColor("#cccccc")
BADGE_EASY   = colors.HexColor("#28a745")
BADGE_MEDIUM = colors.HexColor("#fd7e14")
BADGE_HARD   = colors.HexColor("#dc3545")
BADGE_NA     = colors.HexColor("#6c757d")

PAGE_W, PAGE_H = A4
LEFT_MARGIN = RIGHT_MARGIN = 18 * mm
TOP_MARGIN  = 22 * mm
BOT_MARGIN  = 22 * mm

# ── Style Definitions ─────────────────────────────────────────────────────────

def _build_styles():
    base = getSampleStyleSheet()

    styles = {
        "cover_title": ParagraphStyle(
            "cover_title",
            fontSize=28, leading=34,
            textColor=GFG_DARK, alignment=TA_CENTER,
            spaceAfter=6,
        ),
        "cover_sub": ParagraphStyle(
            "cover_sub",
            fontSize=13, leading=18,
            textColor=GFG_GREEN, alignment=TA_CENTER,
            spaceAfter=4,
        ),
        "cover_meta": ParagraphStyle(
            "cover_meta",
            fontSize=10, leading=14,
            textColor=colors.HexColor("#555555"), alignment=TA_CENTER,
        ),
        "article_title": ParagraphStyle(
            "article_title",
            fontSize=18, leading=22,
            textColor=GFG_DARK,
            spaceAfter=4, spaceBefore=8,
        ),
        "section_heading": ParagraphStyle(
            "section_heading",
            fontSize=11, leading=14,
            textColor=GFG_GREEN,
            spaceAfter=3, spaceBefore=8,
            fontName="Helvetica-Bold",
        ),
        "body": ParagraphStyle(
            "body",
            fontSize=9.5, leading=14,
            textColor=colors.HexColor("#222222"),
            spaceAfter=4,
        ),
        "code_text": ParagraphStyle(
            "code_text",
            fontSize=8, leading=11,
            fontName="Courier",
            textColor=CODE_FG,
            spaceAfter=2,
            backColor=CODE_BG,
            leftIndent=6, rightIndent=6,
        ),
        "ref_item": ParagraphStyle(
            "ref_item",
            fontSize=8.5, leading=12,
            textColor=colors.HexColor("#0066cc"),
            leftIndent=12,
        ),
        "difficulty_easy": ParagraphStyle(
            "difficulty_easy",
            fontSize=9, leading=11,
            textColor=colors.white,
        ),
        "toc_entry": ParagraphStyle(
            "toc_entry",
            fontSize=10, leading=15,
            textColor=GFG_DARK,
            leftIndent=12,
        ),
    }
    return styles


# ── Header / Footer callback ──────────────────────────────────────────────────

class _HeaderFooterCanvas:
    """
    Wraps a canvas to draw a header bar and footer on every page
    (except the cover page).
    """
    def __init__(self, canvas, doc, date_str: str, student_name: str):
        self.canvas = canvas
        self.doc = doc
        self.date_str = date_str
        self.student_name = student_name

    def draw(self):
        c = self.canvas
        page_num = c.getPageNumber()

        if page_num == 1:          # Cover page — no header/footer chrome
            return

        w, h = A4

        # ── Header ────────────────────────────────────────────────────────────
        c.saveState()
        c.setFillColor(GFG_GREEN)
        c.rect(0, h - 14 * mm, w, 14 * mm, fill=1, stroke=0)

        c.setFillColor(colors.white)
        c.setFont("Helvetica-Bold", 9)
        c.drawString(LEFT_MARGIN, h - 9 * mm, SUBJECT_CATEGORY)

        c.setFont("Helvetica", 8)
        c.drawRightString(w - RIGHT_MARGIN, h - 9 * mm, f"Generated: {self.date_str}")
        c.restoreState()

        # ── Footer ────────────────────────────────────────────────────────────
        c.saveState()
        c.setFillColor(colors.HexColor("#f5f5f5"))
        c.rect(0, 0, w, 12 * mm, fill=1, stroke=0)

        c.setStrokeColor(GRAY_LINE)
        c.line(LEFT_MARGIN, 12 * mm, w - RIGHT_MARGIN, 12 * mm)

        c.setFillColor(colors.HexColor("#555555"))
        c.setFont("Helvetica", 7.5)
        c.drawString(LEFT_MARGIN, 4 * mm,
                     f"Generated by: {self.student_name}  |  {GENERATOR_NAME}")
        c.setFont("Helvetica-Bold", 8)
        c.drawRightString(w - RIGHT_MARGIN, 4 * mm, f"Page {page_num}")
        c.restoreState()


# ── Helper flowables ──────────────────────────────────────────────────────────

def _difficulty_badge(difficulty: str, styles: dict) -> Table:
    """Returns a small coloured badge for the difficulty level."""
    low = difficulty.lower()
    if "easy" in low or "basic" in low:
        bg = BADGE_EASY
    elif "medium" in low:
        bg = BADGE_MEDIUM
    elif "hard" in low or "expert" in low:
        bg = BADGE_HARD
    else:
        bg = BADGE_NA

    label = difficulty if difficulty != "Not Available" else "Difficulty: N/A"
    cell = Paragraph(f"<b>{label}</b>", styles["difficulty_easy"])
    t = Table([[cell]], colWidths=[60 * mm], rowHeights=[6 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg),
        ("ROUNDEDCORNERS", [4]),
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING",   (0, 0), (-1, -1), 1),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 1),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return t


def _code_block(snippets: list[str]) -> list:
    """Returns a list of flowables representing a dark-background code block."""
    if snippets == ["Not Available"]:
        return [Paragraph("Not Available", ParagraphStyle(
            "na", fontSize=9, textColor=colors.HexColor("#888888"),
            leftIndent=8
        ))]

    items = []
    for snippet in snippets:
        # Truncate very long snippets for readability in the PDF
        lines = snippet.split("\n")[:40]
        trimmed = "\n".join(lines)
        if len(lines) == 40:
            trimmed += "\n... [truncated]"

        t = Table(
            [[Preformatted(trimmed,
                           ParagraphStyle("pre", fontName="Courier",
                                          fontSize=7.5, leading=10.5,
                                          textColor=CODE_FG))]],
            colWidths=[PAGE_W - LEFT_MARGIN - RIGHT_MARGIN - 4 * mm]
        )
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), CODE_BG),
            ("LEFTPADDING",  (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING",   (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 6),
            ("ROUNDEDCORNERS", [4]),
        ]))
        items.append(t)
        items.append(Spacer(1, 3 * mm))
    return items


# ── Cover page ────────────────────────────────────────────────────────────────

def _cover_page(styles: dict, date_str: str, article_count: int) -> list:
    story = []

    story.append(Spacer(1, 40 * mm))

    # Logo-ish decorative bar
    bar = Table([[""]], colWidths=[80 * mm], rowHeights=[2 * mm])
    bar.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), GFG_GREEN)]))
    # center it
    wrapper = Table([[bar]], colWidths=[PAGE_W - LEFT_MARGIN - RIGHT_MARGIN])
    wrapper.setStyle(TableStyle([("ALIGN", (0, 0), (-1, -1), "CENTER")]))
    story.append(wrapper)
    story.append(Spacer(1, 8 * mm))

    story.append(Paragraph("GeeksforGeeks", styles["cover_sub"]))
    story.append(Paragraph("Linux Operating System", styles["cover_title"]))
    story.append(Paragraph("Academic Learning Module", styles["cover_sub"]))
    story.append(Spacer(1, 6 * mm))

    # Decorative bar (bottom of title)
    story.append(wrapper)
    story.append(Spacer(1, 16 * mm))

    story.append(Paragraph(f"Date of Generation: <b>{date_str}</b>", styles["cover_meta"]))
    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph(f"Subject Category: <b>{SUBJECT_CATEGORY}</b>", styles["cover_meta"]))
    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph(f"Total Articles Covered: <b>{article_count}</b>", styles["cover_meta"]))
    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph(f"Generated by: <b>{GENERATOR_NAME}</b>", styles["cover_meta"]))

    story.append(PageBreak())
    return story


# ── Table of Contents ─────────────────────────────────────────────────────────

def _toc_page(articles: list[dict], styles: dict) -> list:
    story = []
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph("Table of Contents", ParagraphStyle(
        "toc_hd", fontSize=16, leading=20, textColor=GFG_DARK,
        spaceAfter=6, fontName="Helvetica-Bold"
    )))
    story.append(HRFlowable(width="100%", thickness=1.5, color=GFG_GREEN, spaceAfter=6))

    for i, art in enumerate(articles, start=1):
        title = art.get("title", "Untitled")
        story.append(Paragraph(
            f"<b>{i:02d}.</b>  {title}",
            styles["toc_entry"]
        ))

    story.append(PageBreak())
    return story


# ── Per-article section ───────────────────────────────────────────────────────

def _article_section(art: dict, index: int, styles: dict) -> list:
    story = []

    # Article number + title bar
    title_text = f"{index:02d}. {art.get('title', 'Untitled')}"
    title_cell = Paragraph(f"<b>{title_text}</b>", styles["article_title"])

    title_table = Table(
        [[title_cell]],
        colWidths=[PAGE_W - LEFT_MARGIN - RIGHT_MARGIN]
    )
    title_table.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, -1), LIGHT_BG),
        ("LEFTPADDING",  (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING",   (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
        ("BOX",          (0, 0), (-1, -1), 1, GFG_GREEN),
    ]))
    story.append(title_table)
    story.append(Spacer(1, 2 * mm))

    # Difficulty badge
    story.append(_difficulty_badge(art.get("difficulty", "Not Available"), styles))
    story.append(Spacer(1, 3 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_LINE))
    story.append(Spacer(1, 2 * mm))

    # ── Key Technical Concepts ────────────────────────────────────────────────
    story.append(Paragraph("&#9656; Key Technical Concepts", styles["section_heading"]))
    concepts = art.get("concepts", "Not Available")
    story.append(Paragraph(concepts, styles["body"]))
    story.append(Spacer(1, 2 * mm))

    # ── Code Snippets ─────────────────────────────────────────────────────────
    story.append(Paragraph("&#9656; Code Snippets / Implementation", styles["section_heading"]))
    story.extend(_code_block(art.get("code_snippets", ["Not Available"])))

    # ── Complexity Analysis ───────────────────────────────────────────────────
    story.append(Paragraph("&#9656; Complexity Analysis", styles["section_heading"]))
    story.append(Paragraph(art.get("complexity", "Not Available"), styles["body"]))
    story.append(Spacer(1, 2 * mm))

    # ── References / Related Links ────────────────────────────────────────────
    story.append(Paragraph("&#9656; References / Related Links", styles["section_heading"]))
    refs = art.get("references", [{"text": "Not Available", "url": ""}])
    for ref in refs[:6]:               # cap at 6 refs per article
        text = ref.get("text", "")
        url  = ref.get("url", "")
        if url and url != "":
            line = f'{text}  <font size="7" color="#888888">({url})</font>'
        else:
            line = text or "Not Available"
        story.append(Paragraph(f"• {line}", styles["ref_item"]))

    # Section divider
    story.append(Spacer(1, 5 * mm))
    story.append(HRFlowable(width="100%", thickness=1, color=GFG_GREEN, spaceAfter=4))
    story.append(Spacer(1, 4 * mm))

    return story


# ── Main generate function ────────────────────────────────────────────────────

def generate_pdf(articles: list[dict], student_name: str = GENERATOR_NAME) -> str:
    """
    Build the full academic PDF from a list of article dicts.

    Returns the path to the generated PDF file.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    date_str = datetime.now().strftime("%B %d, %Y")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"GFG_Linux_Module_{timestamp}.pdf"
    filepath = os.path.join(OUTPUT_DIR, filename)

    styles = _build_styles()

    # ── Document template with custom header/footer ───────────────────────────
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN + 14 * mm,    # extra space for header bar
        bottomMargin=BOT_MARGIN + 12 * mm, # extra space for footer
        title="GFG Linux Learning Module",
        author=student_name,
        subject=SUBJECT_CATEGORY,
        creator=GENERATOR_NAME,
    )

    # ── Build story ───────────────────────────────────────────────────────────
    story = []

    # Cover
    story.extend(_cover_page(styles, date_str, len(articles)))

    # Table of Contents
    story.extend(_toc_page(articles, styles))

    # Articles
    for i, art in enumerate(articles, start=1):
        story.extend(_article_section(art, i, styles))

    # ── Register header/footer on every page ──────────────────────────────────
    class PageCallback:
        def __init__(self, d, n):
            self.d = d
            self.n = n
        def __call__(self, canvas, doc):
            _HeaderFooterCanvas(canvas, doc, self.d, self.n).draw()

    cb = PageCallback(date_str, student_name)
    doc.build(story, onFirstPage=cb, onLaterPages=cb)

    print(f"[✓] PDF generated: {filepath}")
    return filepath